import { useEffect, useMemo, useState } from "react";
import { Copy, Download, RotateCcw, Upload } from "lucide-react";
import type { ThemeDefinition } from "../domain";
import { downloadJson, pickTextFile } from "../files";
import { parseKittyTheme } from "../themes";
import { Modal } from "./Modal";

const colorLabels = ["Black","Red","Green","Yellow","Blue","Magenta","Cyan","White","Bright black","Bright red","Bright green","Bright yellow","Bright blue","Bright magenta","Bright cyan","Bright white"];
export function ThemeEditor({ themes, selectedId, onSelect, onSave, onDelete, onClose, embedded = false }: { themes: ThemeDefinition[]; selectedId: string; onSelect: (id: string) => void; onSave: (t: ThemeDefinition) => Promise<void>; onDelete: (id: string) => Promise<void>; onClose?: () => void; embedded?: boolean }) {
  const selected = useMemo(() => themes.find((t) => t.id === selectedId) || themes[0], [themes, selectedId]); const [draft, setDraft] = useState(() => structuredClone(selected)); const [importInfo, setImportInfo] = useState("");
  useEffect(() => { if (selected) setDraft(structuredClone(selected)); }, [selected]);
  const patch = (p: Partial<ThemeDefinition>) => setDraft((t) => ({ ...t, ...p })); const palette = (p: Partial<ThemeDefinition["palette"]>) => patch({ palette: { ...draft.palette, ...p } });
  const choose = (id: string) => { onSelect(id); const t = themes.find((x) => x.id === id); if (t) setDraft(structuredClone(t)); };
  const clone = () => setDraft({ ...structuredClone(draft), id: crypto.randomUUID(), name: `${draft.name} Custom`, builtIn: false });
  const importFile = async () => { const file = await pickTextFile(".conf,.json"); if (!file) return; try { if (file.name.endsWith(".json")) setDraft(JSON.parse(file.text)); else { const out = parseKittyTheme(file.text, file.name.replace(/\.conf$/, "")); setDraft(out.theme); setImportInfo(out.ignored.length ? `Ignored unsupported settings: ${out.ignored.join(", ")}` : "All settings imported."); } } catch { setImportInfo("This theme file could not be read."); } };
  const download = () => downloadJson(`${draft.name.toLowerCase().replace(/\W+/g,"-")}.sesh-theme.json`, JSON.stringify(draft, null, 2));
  const chooseBackground = () => { const input=document.createElement("input");input.type="file";input.accept="image/png,image/jpeg,image/webp,image/gif";input.onchange=()=>{const file=input.files?.[0];if(!file)return;if(file.size>5_000_000){setImportInfo("Background images must be smaller than 5 MB.");return}const reader=new FileReader();reader.onload=()=>patch({backgroundImage:String(reader.result)});reader.readAsDataURL(file)};input.click(); };
  const content = <div className={`theme-layout${embedded ? " embedded" : ""}`}><aside className="theme-list">{themes.map((t) => <button className={t.id === selectedId ? "active" : ""} onClick={() => choose(t.id)} key={t.id}><span className="swatch" style={{background: `linear-gradient(135deg,${t.palette.background} 50%,${t.palette.ansi[4]} 50%)`}}/><span>{t.name}<small>{t.builtIn ? "Curated" : "Custom"}</small></span></button>)}</aside>
    <div className="theme-editor"><div className="theme-toolbar"><input className="theme-name" value={draft.name} disabled={draft.builtIn} onChange={(e) => patch({name:e.target.value})}/><button className="button secondary" onClick={clone}><Copy size={15}/>Clone</button><button className="icon-button" title="Import Kitty or Sesh theme" onClick={importFile}><Upload size={16}/></button><button className="icon-button" title="Export theme" onClick={download}><Download size={16}/></button></div>
      {importInfo && <p className="info-banner">{importInfo}</p>}
      <div className="terminal-preview" style={{background:draft.palette.background,color:draft.palette.foreground,fontFamily:draft.fontFamily,fontSize:draft.fontSize,lineHeight:draft.lineHeight}}><span style={{color:draft.palette.ansi[2]}}>alex@sesh</span><span style={{color:draft.palette.ansi[6]}}> ~/project</span> <span style={{color:draft.palette.ansi[5]}}>git:(main)</span><br/><span style={{color:draft.palette.cursor}}>❯</span> npm run dev<span className="preview-cursor" style={{background:draft.palette.cursor}}/></div>
      <section className="setting-section"><h3>Colors</h3><div className="color-grid"><Color label="Foreground" value={draft.palette.foreground} onChange={(foreground) => palette({foreground})}/><Color label="Background" value={draft.palette.background} onChange={(background) => palette({background})}/><Color label="Cursor" value={draft.palette.cursor} onChange={(cursor) => palette({cursor})}/><Color label="Selection" value={draft.palette.selectionBackground} onChange={(hex) => palette({selectionBackground: hex + draft.palette.selectionBackground.slice(7)})}/>{draft.palette.ansi.map((value,i) => <Color key={i} label={colorLabels[i]} value={value} onChange={(v) => { const ansi=[...draft.palette.ansi]; ansi[i]=v; palette({ansi}); }}/>)}</div></section>
      <section className="setting-section"><h3>Typography</h3><div className="setting-grid"><Field label="Font family"><input value={draft.fontFamily} onChange={(e)=>patch({fontFamily:e.target.value})}/></Field><Field label="Size"><input type="number" min="8" max="40" value={draft.fontSize} onChange={(e)=>patch({fontSize:Number(e.target.value)})}/></Field><Field label="Weight"><select value={draft.fontWeight} onChange={(e)=>patch({fontWeight:Number(e.target.value)})}><option value="300">Light</option><option value="400">Regular</option><option value="500">Medium</option><option value="600">Semi-bold</option><option value="700">Bold</option></select></Field><Field label="Line height"><input type="number" step="0.05" min="1" max="2" value={draft.lineHeight} onChange={(e)=>patch({lineHeight:Number(e.target.value)})}/></Field></div></section>
      <section className="setting-section"><h3>Cursor & layout</h3><div className="setting-grid"><Field label="Cursor"><select value={draft.cursorStyle} onChange={(e)=>patch({cursorStyle:e.target.value as ThemeDefinition["cursorStyle"]})}><option value="block">Block</option><option value="bar">Beam</option><option value="underline">Underline</option></select></Field><Field label="Padding"><input type="number" min="0" max="48" value={draft.padding} onChange={(e)=>patch({padding:Number(e.target.value)})}/></Field><Field label={`Background opacity ${Math.round(draft.backgroundOpacity*100)}%`}><input type="range" min="0.35" max="1" step="0.01" value={draft.backgroundOpacity} onChange={(e)=>patch({backgroundOpacity:Number(e.target.value)})}/></Field><label className="check"><input type="checkbox" checked={draft.cursorBlink} onChange={(e)=>patch({cursorBlink:e.target.checked})}/> Blinking cursor</label><div className="field"><span>Background image</span><div className="background-actions"><button className="button secondary" type="button" onClick={chooseBackground}>{draft.backgroundImage?"Replace image":"Choose image"}</button>{draft.backgroundImage&&<button className="button secondary" type="button" onClick={()=>patch({backgroundImage:undefined})}>Remove</button>}</div></div><Field label={`Image opacity ${Math.round(draft.backgroundImageOpacity*100)}%`}><input type="range" min="0" max="1" step="0.01" value={draft.backgroundImageOpacity} disabled={!draft.backgroundImage} onChange={(e)=>patch({backgroundImageOpacity:Number(e.target.value)})}/></Field></div></section>
      <footer className="modal-actions"><button className="button danger" disabled={draft.builtIn} onClick={() => onDelete(draft.id)}>Delete</button><span className="grow"/><button className="button secondary" onClick={() => setDraft(structuredClone(selected))}><RotateCcw size={15}/>Reset</button><button className="button primary" onClick={() => onSave(draft)}>Save theme</button></footer>
    </div></div>;
  return embedded ? content : <Modal title="Terminal appearance" wide onClose={onClose || (() => {})}>{content}</Modal>;
}
function Color({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}) { return <label className="color-field"><input type="color" value={value.slice(0,7)} onChange={(e)=>onChange(e.target.value)}/><span>{label}</span><code>{value.slice(0,7)}</code></label> }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="field"><span>{label}</span>{children}</label> }
